# Generated by Django 6.0.6 on 2026-06-10 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_aset', models.CharField(max_length=20, unique=True)),
                ('nama_kendaraan', models.CharField(max_length=100)),
                ('jenis', models.CharField(max_length=50)),
                ('km_terakhir', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Perawatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_perawatan', models.CharField(choices=[('ganti_oli', 'Ganti Oli'), ('servis_rutin', 'Servis Rutin'), ('ganti_ban', 'Ganti Ban'), ('servis_besar', 'Servis Besar'), ('lainnya', 'Lainnya')], max_length=50)),
                ('tanggal', models.DateField()),
                ('km_saat_servis', models.IntegerField()),
                ('catatan', models.TextField(blank=True)),
                ('dicatat_oleh', models.CharField(max_length=100)),
                ('next_service_km', models.IntegerField(blank=True, null=True)),
                ('next_service_tanggal', models.DateField(blank=True, null=True)),
                ('is_anomali', models.BooleanField(default=False)),
                ('pesan_anomali', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('aset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenance.aset')),
            ],
            options={
                'ordering': ['-tanggal'],
            },
        ),
    ]
